### ISSUE TITLE
Configure image service and AGOL account

### ISSUE THREAD

**Issue by ebonan** [Esri/Imagery-Apps#1]
We downloaded and deployed the web app following instructions.

Looking at the config file we noticed that the  image service URL is empty (while Landsat explore is preconfigured to ponit at Esri landsat image services)

So we  add the following URL  "https://sentinel.arcgis.com/arcgis/rest/services/Sentinel2/ImageServer "and it works.
but when we try to  use the time selector widget  a  " NaN undefined NaN " error apepar in the form (see attached image).

We have seen that this feature depends on AGOL account so we sign in with our subscriprion credential but the error continue to appear.

Looking at network traffic (by firebug) we noticed   a worning regarding AGOL credential and token ..

Please could you give us help and a correct sample of config file settings ?
thank you
Enrico
![15](https://user-images.githubusercontent.com/3044156/42093464-aec2c340-7bac-11e8-9e14-bee49fac0608.png)
![error_firebug](https://user-images.githubusercontent.com/3044156/42093874-2fa4d4f2-7bae-11e8-92d0-6e6400966d9f.jpg)

**Comment by kushu493** [comment]
Hi,

Sorry for late reply. We have just updated both the apps. Can you please try again with these updated apps and see whether the issue still persists.
